[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.9.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.1"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.9.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.1"

[[constraint]]
  name = "github.com/go-resty/resty"
  version = "1.3.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  name = "github.com/howeyc/fsnotify"
  version = "0.9.0"
