apiVersion: v1
kind: ConfigMap
metadata:
  name: initializer-config
  namespace: default
data:
  config.yaml: |-
    container-image: wanderadock/scccmd:v0.0.2
    default:
      label: master
      profile: development
      source: http://config-manager-controller.default.svc:8080
      volume-mount: /config
      volume-name: config
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: config-injector-cert
data:
  private.key: ''
  publickey.cer: ''
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-injector
spec:
  selector:
    matchLabels:
      app: config-injector
  template:
    metadata:
      labels:
        app: config-injector
    spec:
      containers:
      - name: config-injector-initializer
        image: wanderadock/scccmd:v0.0.2
        args:
        - webhook
        - --config-file
        - /config/config.yaml
        - --cert-file
        - /keys/publickey.cer
        - --key-file
        - /keys/private.key
        volumeMounts:
        - name: config-volume
          mountPath: /config
          readOnly: true
        - name: keys-volume
          mountPath: /keys
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: config-injector-config
      - name: keys-volume
        secret:
          secretName: config-injector-cert
---
apiVersion: v1
kind: Service
metadata:
  name: config-injector
spec:
  ports:
  - port: 443
    name: https
  selector:
    app: config-injector
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: config-injector-webhook
webhooks:
  - name: config.scccmd.github.com
    failurePolicy: Fail
    clientConfig:
      service:
        name: config-injector
        namespace: default
        path: "/inject"
      caBundle: ''
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        inject: true
